package-lock.json, package.json, pages/_app.js, postcss.config.js, styles/globals.css, tailwind.config.js
- install autoprefixer, postcss and tailwindcss
- add contents in tailwind.config.js
- add tailwind directives in /styles/globals.css
- add tailwindcss import in /pages/_app.js
=> Add tailwindcss to the project

components/homepage/Card.js, pages/index.js
- add basic layout for the orgs section
- add comments for readability (dev)
=> Add basic layout of "Participating Org section"

package-lock.json, package.json, pages/_app.js, pages/api/data.js, pages/diabloAccordion.js, pages/faq.js
Styling is still required
@Anubhavdevv @swapnilsparsh
=> Added Chakra Accordion & FAQ data

components/BackToTopButton.js, components/Layout.js, package-lock.json, package.json, pages/index.js
- add styled component for easy conditinal CSS classes
- add BackToTopButton.js component
- add BackToTopButton app-wide in Layout.js
=> feat: add back to top button

pages/api/scheduleData.js
Suvraneel sir merge my Pull Request
=> Edited the Schedule for GSSoC'22

components/Navbar.js, pages/faq.js, pages/index.js, pages/project.js, pages/schedule.js, pages/team.js
=> Added Indepentent Headers for Every Page for GSSoC Website

pages/api/FAQdata.js, pages/team.js
Would you mind counting my contribution in the program's schedule of 3 months? XD
=> Updates in FAQ and Team section for GSSoC'22

components/Navbar.js, pages/faq.js, pages/index.js, pages/project.js, pages/schedule.js, pages/team.js
Reverts girlscript/gssoc-website-new#51
=> Revert "Added Indepentent Headers for Every Page for GSSoC Website"

components/Navbar.js, pages/faq.js, pages/index.js, pages/project.js, pages/schedule.js, pages/team.js
Reverts girlscript/gssoc-website-new#54
=> Revert "Revert "Added Indepentent Headers for Every Page for GSSoC Website""

pages/leaderboard.js
Removed unwanted code, fixed breaking actions
=> Fixed Break On User Row Click

pages/leaderboard.js
Changed the prod leaderboard URL to a stable Heroku project
=> Changed Leaderboard Prod URL

components/BackToTopButton.js, components/ChatwootWidget.js, pages/_app.js, pages/blog.js
Closed #70 
Real-Time Chatbot feature with Chatwoot application, user can ask queries that are common, but in this at the end of the chat user can give you feedback and there was an extra feature if the user wants to add some files like images gif something to they can add by attaching button given there. And changes the scroll to the top button position on the left side
You can access chats by creating an account on Chatwoot,  I don't have a subscription so right now I can only add a single member as Admin In Chatwoot account
https://user-images.githubusercontent.com/73753957/161401938-39b5b517-a5ab-4ae5-9cbc-520a4f97e1a4.mp4
=> feat: live chatbot added

pages/leaderboard.js, styles/globals.css
**Issue Fixed :- #79**
Work done :- 
1. Fixed PR links
2. Added view btn to rows
3. Fixed modal for dark theme (Wasn't theme consistent)
4. Added :hover underline for username
Please find attached video below for your reference
https://user-images.githubusercontent.com/54144759/164657723-70216946-499b-44c9-ad06-fb01f4750565.mp4
=> Fixed PR links and added view Button

package-lock.json, package.json, pages/leaderboard.js, styles/globals.css
Issue resolved #78 
Working perfectly for search and normally
Please find attached below a working video for your reference
https://user-images.githubusercontent.com/54144759/164949095-1b4a296a-a3e0-495c-941a-31e0f782c891.mp4
=> added pagination

README.md
This PR fixes issue #96 . Kindly have a look
=> Fix Image not rendering in README

README.md
Reverts girlscript/gssoc-website-new#97
=> Revert "Fix Image not rendering in README"

pages/project.js
Closes : #109
Hey have added the feature that makes card to shuffle on every render 
Plz review it 
Thanks
=> feat: Add randomize or shuffle to cards

components/Navbar.js, pages/leaderboard.js
- Server deployments managed on Render
- Updates Every 12 hours automatically
=> [Leaderboard] Provisioning Leaderboard for 2023 🎉

.github/workflows/gssoc-deploy.yml
=> ci: upgrade to node lts hydrogen

pages/index.js
social float is now responsive
=> Issue #117 solved

pages/team.js
Issue Resolved #127 
@Suvraneel Kindly merge this PR
=> add hover effect to team cards

components/homepage/Card.js
#126 fixed @Suvraneel  Please Review this PR
=> fixed cards alignment

pages/index.js
@Suvraneel Can your review this PR and suggest changes if you want any #100 solved
=> fixed ThemeBtn in md Screens

pages/leaderboard.js, styles/globals.css
=> overlapping fixed

pages/index.js
- Registration & Participation Stats updated
=> stats updated for 2023

pages/api/leaderboard23.json
Added the final leaderboard for 2023
=> [2023] Final Leaderboard

pages/index.js
changed in the index file in 2023 to 2024.
=> update:2024 in index file

components/Footer.js, pages/jobfair.js
#161 Changed 2023  to 2034 .
Updated the "Register Now" google form link.
=> Update : Job Fair section

components/MoreMenu.js, components/Navbar.js
=> fixed: dropdown moblie view

components/MoreMenu.js, components/Navbar.js, public/team_data/team2024.json
=> Update team data 2024

components/MoreMenu.js, components/Navbar.js, pages/index.js, public/team_data/team2024.json
=> Update : Sponsors 2023

components/diabloAccordion.js, pages/api/FAQdata.js, pages/faq.js
- Added 5 FAQs
- Refactored code for DiabloAccordion
=> Updated : FAQs

components/homepage/SocialFollow.js
Solves #114 
Changes the social icons to white and it actually fits in the color pallet acc to me:
=> updated socialfollow.js : Solves #114

public/team_data/team2024.json
Removed Subroto Banerjee (Sponsership) from gssoc website.
=> Updated Team details

contributors.md
Updated the latest event with Yati Padia on the events page
=> Updated the Event page

.eslintrc.json
- Bypassed eslint rules to move project into build
=> Build Fail due to Image component no longer a prolem

pages/index.js, public/team_data/team2024.json
Changed starting date from 5th May to !0th May.
=> Changed Starting Date

pages/index.js, public/team_data/team2024.json
=> Changed Registration Link

pages/project.js
Fixes : #205 
This PR fixes the heading year change issue.
https://github.com/girlscript/gssoc-website-new/assets/90561803/4a79f98a-488f-4007-8656-f8892e730b55
=> Fixed heading on yar change in projects

components/Footer.js
#203 Updated the link as mentioned on the issue
=> Update Footer.js with right link on image

pages/project.js
=> fixes empty pill for projects techstack

components/homepage/Card.js
the color of the buttons for applying as a contributor, mentor, and organization is incorrect. so correct this
=> Update color  buttons  Card.js

components/homepage/Card.js, pages/contact.js
in contact page social icon not working and not linked so i fixed this
=> contact page social icon not working

pages/api/projectTags.js
I have solved the issue on the project page. Where on clicking the tailwind the projects are not getting filtered.
Issue no #219
=> Tailwind CSS Search box issue fixed

pages/project.js
=> Refactor: Combined repetitive functions into a single one

pages/blog.js, pages/campus_ambassador.js, pages/codeofconduct.js, pages/faq.js, pages/info.js, pages/jobfair.js, pages/leaderboard.js, pages/project.js, pages/schedule.js, pages/verify_cert.js
Updated All the Years in all the possible Pages
Kindly Mark this issue as GSSoC and Merge My PR
Thank You
=> Wrong Year in Title

pages/index.js
@sanjay-kv 
As Discussed in https://github.com/girlscript/gssoc-website-new/pull/240 I have created issue #241
I Changed
27000+ registration
17000+ participants
20+ countries
200+ institutions
205 + projects
=> Done Changing the stats #241

pages/index.js
I changed into
27000+ registration
17000+ participants
20+ countries
200+ institutions
205 + projects
and also changed 2023 -> 2024 in index.js
=> Changing the stats #241

pages/leaderboard.js
=> fix: UI bug with badges with score less than 60 #247 

pages/leaderboard.js
Issue No: #255
Now The list will be filtered every time the user enters the value in the search bar on the LeaderBoard section
**If it's not good, please assign me again I will do it better**
https://github.com/girlscript/gssoc-website-new/assets/121508628/e5435be8-3590-4939-a777-b59f6c23bb8e
=> [Feat]: Enhancement the LeaderBoard searchbar

components/BackToTopButton.js
Hey @sanjay-kv  | Issue Closes #271 
This PR enhances the **user interface and user experience** of the **scroll-to-top button** on the **GirlScript Summer of Code (GSSoC) website.** 
The previous implementation of the button was functional but 
- **Lacked visual appeal**, 
- **Does not match the website design theme** and responsiveness. 
This update aims to improve both the **aesthetics** and **usability** of the button.
- I have used **React.js with styled-components** for **dynamic styling and animations**.
- **Utilized keyframes** in styled-components to create smooth and responsive animations for the button.
- Updated the button styling to use a **round shape** with **increased size** `42px diameter`.
- **Changed the button color scheme** to Match website's design theme. `#FF6024` …
=> Enhanced "Scroll-to-Top Button" UI/UX Matching to "Website's Design" Theme

components/BackToTopButton.js, components/Layout.js, components/ScrollProgressBar.js, styles/globals.css
Hey @sanjay-kv | Issue Closes #273 
This pull request introduces a new scroll progress bar feature to the Girlscript Summer of Code (GSSOC) website, enhancing navigation and user experience on long pages such as "About GSSOC," "Teams," "Services," "Sponsors," "Projects," "Blogs," and "Leaderboard" etc
- Created a new `ScrollProgressBar` component in `components/ScrollProgressBar.js.`
- The component calculates the user's scroll position and updates the progress bar width accordingly.
- Added styles for the scroll progress bar into `styles/global.css` for consistent application across the site.
The issue I face was that whenever I scroll down and the bar updates, it remains same when I navigate to the other pages
to overcome that issue:
- I Added logic to reset the progress bar state when …
=> Implement "Scroll Progress Bar" for Improved User Experience

pages/leaderboard.js
changed the search input to a normal text input and added an extra clear input button. 
Now it resets the page when search bar is cleared.
Closes #276
=> BUG: Fixed the Clear Search button

components/wob/UnderConstruction.js, pages/wob.js
Coming soon page is linked to wob.
=> Comming soon wob

pages/project.js
=> feat: project page details added

package.json, pages/project.js
=> Improve Projects Page

package.json, pages/project.js
Reverts girlscript/gssoc-website-new#294
=> Revert "Improve Projects Page"

pages/contact.js
The "Contact Us" page text features a subtle animation that draws attention with a gentle pulsing effect, making it more noticeable to visitors. This engaging animation encourages users to interact and reach out, enhancing the overall user experience.
https://github.com/girlscript/gssoc-website-new/assets/95361125/71b0eed1-0359-4104-bf75-00f212d36b54
close #279
=> update contact page

components/wob/SnowfallEffect.js, components/wob/SnowfallEffect.module.css
Made the snow fall as realistic as possible.
=> SNOW FALL EFFECT

components/Footer.js, pages/api/wobcodeofconductData.js, pages/wobCodeofConduct.js
WOB Code of conduct page is added.
[Issue Link](https://github.com/girlscript/gssoc-website-new/issues/313) resolve #313
=> Adding code of Conduct: WOB  Added

pages/leaderboard.js
On hovering on the badges one can find the share button and download button.
Closes #269
=> Added Share and Download Button to the Badges

components/diabloAccordion.js, pages/faq.js, styles/faq.module.css
- New UI styles added for The Faqs page
- Tailwind CSS used
- Heading nbsp fixed
- Dark theme colors revised
closes #292
=> FAQs Updated with new UI

pages/leaderboard.js
=> solved the part for light theme

.github/workflows/gssoc-deploy.yml, package-lock.json, package.json, pages/contact.js, pages/leaderboard.js, pnpm-lock.yaml
After many tests. the problem is there is error in the eslint and and some modules. No I fixed build related error and leaderboard.
=> deployment and leaderborad Fix

components/BackToTopButton.js, components/Footer.js, components/Navbar.js, components/ScrollProgressBar.js, pages/_app.js, pages/wob.js
This is website launching pr. merge this pr just before launching.
**Note** 
first merge #310  then merge this.
=> LAUNCH WOB Website

pages/leaderboard.js, pages/user/[...name].js
I have created the leaderboard like shown in the image 
closes : #293 
https://github.com/user-attachments/assets/bb9ce8b1-39e2-47e2-85ba-6d2be4ab5945
Sir i have created a functional leaderboard and have used a github api endpoints but these have limited access 
If you found any mistake or want to change anything then please let me know
=> Improved the Leaderboard Stats

components/Navbar.js, pages/user/[...name].js
@sanjay-kv  Sir i fixed that and it should work please check 
#326
=> Fixed Deployment Error 

package-lock.json, package.json, pages/project.js, pnpm-lock.yaml
Close: #289 
Preview: https://gssoc-website-new.vercel.app/project
=> Fix Project Page Issues

pages/leaderboard.js, pages/user/[username].js
Reverts girlscript/gssoc-website-new#333
=> Revert "fix 404 in User Page"

components/diabloAccordion.js, pages/api/FAQdata.js
Hey @sanjay-kv 
- Issue fixes #324
This pull request addresses several key issues and enhancements on the GSSoC FAQ page:
**Files Changed:**
- `DiabloAccordion.js`
- `FAQdata.js`
After refreshing the page, the FAQ section (Accordion only) was switching to dark mode while other components remained in light mode. 
https://github.com/user-attachments/assets/29a390c9-6788-4eaf-a0e4-0d5e1141e8f9
**To fix this I have:**
- Applied conditional styling based on `isDarkMode`. and the solution is:
https://github.com/user-attachments/assets/1f9f5a46-6b39-43f0-a23a-bb73d0376507
The FAQ accordion's text color and background color were inconsistent between light and dark modes, causing readability issues. 
**To fix this I have made the following changes:**
**In Light Mode:**
- Question text color: …
=> Fixed Issues and Bugs on GSSoC FAQ Page 

pages/event.js
=> Event page problems resolved

.github/workflows/gssoc-deploy.yml
Updated the workflow to store github access token and check that token is exist or not.
=> Related to token

pages/leaderboard.js
=> fixes #338 Invalid Tooltip for badges

pages/wob.js
This is the minor update related to wob website. Updated the dates given.
=> minor update

components/Footer.js, components/MoreMenu.js, components/Navbar.js, pages/wobContact.js
updated the nav bar and added the contact us page for wob website.
=> Navbar and contact us page.

components/homepage/Card.js, pages/wob.js
Be a part of us in landing page is edited as cards as in GSSoC for Contributors, project admin, mentors and sponsers updated.
=> Landing page of wob update

pages/wobTeam.js, public/WoB/wob_team/team2024.json
wob teams page is updated with social media managers.
=> wob teams update

components/Navbar.js, pages/contact.js
- As seen in the video attached below, the hover effect was not working on the `WOB` element of the navbar, so I have fixed this issue
- The gmail in the contact page didn't had cursor pointer whereas the contact number had, so added cursor pointer to contact gmail as well
https://github.com/user-attachments/assets/bba86122-3d79-4a4c-a533-ab62e8a3ce43
=> Fixes hover effect on WOB in navbar

pages/leaderboard.js, styles/globals.css
Closes: https://github.com/GSSoC24/being-an-GSSoc24/issues/167
Enhanced pagination as per the issue: https://github.com/GSSoC24/being-an-GSSoc24/issues/167
Demo video:
https://github.com/user-attachments/assets/efd741fc-8b4f-426e-822e-570a272a5ab3
=> Refactored Pagination on the leaderboard✨

components/Navbar.js, pages/registration.js
This PR adds Seconds to the Countdown with Text to Indicate Hours,Mins,Second
**Preview -** 
N/A
=> Addded Seconds to the Countdown with Text to Indicate Hours,Mins,Second

pages/registration.js
This PR fixes the responsiveness for Counter of other roles than CA.
**Before:**
**Fixed:**
N/A
=> Fixed Responsiveness for Counter

pages/registration.js
=> Changed text color of select box in dark mode

public/team_data/team2024.json, public/team_data/team2024Extd.json, public/team_member_data/member_data.json
Closes: https://github.com/GSSoC24/being-an-GSSoc24/issues/192
- Updated Sowmiya's Profile as asked by her
- Name changed to Sowmiya V fom Sowmiya Venkatesan
- Designation fixed
=> Update Sowmiya Profile

pages/registration.js
=> Fix: Registration page Dark mode input field issue 

pages/sponsorUs.js
=> Fix Sponsor Us page Darkmode styling

utils/models/contributorsSchema.js, utils/models/mentorSchema.js, utils/models/projectAdminSchema.js
Description:
Fixes Required Year Field for PA,Mentor,Contributor
=> Updated Year Requirement form Schemas

styles/globals.css
closes [issue](https://github.com/GSSoC24/being-an-GSSoc24/issues/171)
=> Alligned vertical scroll bar with our current theme of website

pages/api/registration.js
This PR fixes the body of mail that was incorrect for PA,Mentor and Contributor
N/A
=> Fixed Mail Message

pages/index.js
Earlier on the `Register Here` button in the About page, anchor tag was used which caused reloading of the tab on click, instead I replaced with Link tag which avoids loading and directly redirects to the desired page optimizing the performance and user experience
=> Replaced anchor tag with Link tag to avoid loading and optimize performance

components/diabloAccordion.js, pages/faq.js
BEFORE:
https://github.com/user-attachments/assets/8f37fa15-3135-499a-8922-178492846736
- Can be seen in the video, after switching to dark mode if we refresh, the styling changes to light mode styling
AFTER:
- Dark mode working even after refresh proof 
https://github.com/user-attachments/assets/72943512-0c92-4bea-a832-64cec99d88e6
- light mode working proof
https://github.com/user-attachments/assets/59769c62-dfe1-4427-9c63-c3d5a36a18d3
BUG noticed by @MastanSayyad
=> [BUG] Fixes FAQ Page dark mode issue after refreshing

components/PopupBanner.js
=> Popup Visit here btn not working fixed

pages/_app.js
This PR integrates Google Analytics tracking into the web app using the GA Measurement ID.
**Issue Mentioned:**
Closes: https://github.com/GSSoC24/being-an-GSSoc24/issues/211\
**File Changes:**
Modified: pages/_app.js to include google analytics in the head tag.
N/A
=> Feat: Added Google Analytics

components/Layout.js, components/ModuleDetails.js, components/ModuleList.js, components/VideoPlayer.js, package-lock.json, package.json, pages/api/gssocAcademyData.js, pages/gssoc_academy.js
Route: /gssoc_academy
psuedo code
not yet completed
basic structure implementation done
=> Adding setup of GSSOC Academy

pages/registration.js
This PR adds form validation on the second slide of the registration page.
**Video:**
https://github.com/user-attachments/assets/112636b8-f0a6-4607-ba27-bec14fdf9011
Its tested but once test it out again
=> Added form field validation before moving to next slide in registrations

package-lock.json, pages/project.js
Hey @sanjay-kv, @Hemu21, @MastanSayyad, @RadhikaMalpani1702 ,@suhanipaliwal 
closes [issue](https://github.com/GSSoC24/being-an-GSSoc24/issues/214)
- Centered the heading properly.
- Added responsive design to ensure the layout adapts well on all screen sizes.
- Moved the search bar to the correct position below the "Project Years Sections."
https://github.com/user-attachments/assets/ad8f55e9-dea8-4f1d-b5c2-fb9e9d04953c
=> ✅Fixed Alignment and Responsiveness Issues on Projects Page 

pages/teamprofile.js, public/team_member_data/member_data.json
closes https://github.com/GSSoC24/being-an-GSSoc24/issues/202
Old PR https://github.com/girlscript/gssoc-website-new/pull/414
@Hemu21 @MastanSayyad @sanjay-kv 
https://github.com/user-attachments/assets/8d622bef-29db-438f-b7ce-de2be38251c3
=> 1:1 Mentorship Button Bug is Fixed Finally 

package-lock.json, pages/registration.js
This PR adds the Registrations Closed Page for Campus Ambassadors to provide better context to the users.
**Screenshots:**
N/A
=> Added Registrations Closed Page for CA

pages/registration.js
This PR changes the Registration's page slide-1 design to a new card based design.
**Issue Mentioned:**
https://github.com/GSSoC24/being-an-GSSoc24/issues/217
**Screenshots:**
**Video:**
https://github.com/user-attachments/assets/bad028e8-8645-456b-914e-5d359440fd6a
N/A
=> Enhancement: Changed First Slide's Design of Registration Page

pages/registration.js
Added msg "Maximum Size 1MB" in the registration page Resume upload msg
=> Size constraint for resume upload

pages/badgeId.js
Removes Trailing and Leading spaces from input fields to prevent verfication fail in case user enters spaces
N/A
=> Fixes Badge Input Fields

pages/registration.js
Opened the form again for CA registrations
=> CA registrations opened

pages/caLeaderboard.js
Added CA Leaderboard Coming Soon msg
⬇️
=> Added CA Leaderboard Coming Soon msg

pages/api/caLeaderboards.js, pages/api/registration.js, pages/caLeaderboard.js, utils/models/caLeaderboard.js
This PR adds Realtime Updation of CA Leaderboards, as soon as a user submits a registration with a referralCode it will be directly updated in the CA Leaderboards collection stored in MongoDB making the CA Leaderboards Realtime.
N/A
=> Added Realtime CA Leaderboards Feature

pages/caLeaderboard.js
Merge it when CA Leaderboards needs to be open.
N/A
=> Open CA Leaderboard

pages/caLeaderboard.js
This PR fixes the CA Leaderboard's Rank bug when user searches something.
**Issue Mentioned:**
https://github.com/GSSoC24/being-an-GSSoc24/issues/222
N/A
=> Fixed CA Leaderboard Rank Issue

pages/registration.js
Description:
This PR closes the PA and Mentor Registrations
Additional Context:
N/A
=> Close Registrations for PA and Mentors
